/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.kafka.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class AssignmentNotification extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7074012416190840097L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AssignmentNotification\",\"namespace\":\"com.kafka.avro\",\"fields\":[{\"name\":\"mentor\",\"type\":{\"type\":\"record\",\"name\":\"Mentor\",\"fields\":[{\"name\":\"mentorName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"mentorEmail\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}},{\"name\":\"students\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Student\",\"fields\":[{\"name\":\"studentName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"studentEmail\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AssignmentNotification> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AssignmentNotification> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AssignmentNotification> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AssignmentNotification> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AssignmentNotification> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AssignmentNotification to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AssignmentNotification from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AssignmentNotification instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AssignmentNotification fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private com.kafka.avro.Mentor mentor;
  private java.util.List<com.kafka.avro.Student> students;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AssignmentNotification() {}

  /**
   * All-args constructor.
   * @param mentor The new value for mentor
   * @param students The new value for students
   */
  public AssignmentNotification(com.kafka.avro.Mentor mentor, java.util.List<com.kafka.avro.Student> students) {
    this.mentor = mentor;
    this.students = students;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return mentor;
    case 1: return students;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: mentor = (com.kafka.avro.Mentor)value$; break;
    case 1: students = (java.util.List<com.kafka.avro.Student>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'mentor' field.
   * @return The value of the 'mentor' field.
   */
  public com.kafka.avro.Mentor getMentor() {
    return mentor;
  }


  /**
   * Sets the value of the 'mentor' field.
   * @param value the value to set.
   */
  public void setMentor(com.kafka.avro.Mentor value) {
    this.mentor = value;
  }

  /**
   * Gets the value of the 'students' field.
   * @return The value of the 'students' field.
   */
  public java.util.List<com.kafka.avro.Student> getStudents() {
    return students;
  }


  /**
   * Sets the value of the 'students' field.
   * @param value the value to set.
   */
  public void setStudents(java.util.List<com.kafka.avro.Student> value) {
    this.students = value;
  }

  /**
   * Creates a new AssignmentNotification RecordBuilder.
   * @return A new AssignmentNotification RecordBuilder
   */
  public static com.kafka.avro.AssignmentNotification.Builder newBuilder() {
    return new com.kafka.avro.AssignmentNotification.Builder();
  }

  /**
   * Creates a new AssignmentNotification RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AssignmentNotification RecordBuilder
   */
  public static com.kafka.avro.AssignmentNotification.Builder newBuilder(com.kafka.avro.AssignmentNotification.Builder other) {
    if (other == null) {
      return new com.kafka.avro.AssignmentNotification.Builder();
    } else {
      return new com.kafka.avro.AssignmentNotification.Builder(other);
    }
  }

  /**
   * Creates a new AssignmentNotification RecordBuilder by copying an existing AssignmentNotification instance.
   * @param other The existing instance to copy.
   * @return A new AssignmentNotification RecordBuilder
   */
  public static com.kafka.avro.AssignmentNotification.Builder newBuilder(com.kafka.avro.AssignmentNotification other) {
    if (other == null) {
      return new com.kafka.avro.AssignmentNotification.Builder();
    } else {
      return new com.kafka.avro.AssignmentNotification.Builder(other);
    }
  }

  /**
   * RecordBuilder for AssignmentNotification instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AssignmentNotification>
    implements org.apache.avro.data.RecordBuilder<AssignmentNotification> {

    private com.kafka.avro.Mentor mentor;
    private com.kafka.avro.Mentor.Builder mentorBuilder;
    private java.util.List<com.kafka.avro.Student> students;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.kafka.avro.AssignmentNotification.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.mentor)) {
        this.mentor = data().deepCopy(fields()[0].schema(), other.mentor);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (other.hasMentorBuilder()) {
        this.mentorBuilder = com.kafka.avro.Mentor.newBuilder(other.getMentorBuilder());
      }
      if (isValidValue(fields()[1], other.students)) {
        this.students = data().deepCopy(fields()[1].schema(), other.students);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing AssignmentNotification instance
     * @param other The existing instance to copy.
     */
    private Builder(com.kafka.avro.AssignmentNotification other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.mentor)) {
        this.mentor = data().deepCopy(fields()[0].schema(), other.mentor);
        fieldSetFlags()[0] = true;
      }
      this.mentorBuilder = null;
      if (isValidValue(fields()[1], other.students)) {
        this.students = data().deepCopy(fields()[1].schema(), other.students);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'mentor' field.
      * @return The value.
      */
    public com.kafka.avro.Mentor getMentor() {
      return mentor;
    }


    /**
      * Sets the value of the 'mentor' field.
      * @param value The value of 'mentor'.
      * @return This builder.
      */
    public com.kafka.avro.AssignmentNotification.Builder setMentor(com.kafka.avro.Mentor value) {
      validate(fields()[0], value);
      this.mentorBuilder = null;
      this.mentor = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'mentor' field has been set.
      * @return True if the 'mentor' field has been set, false otherwise.
      */
    public boolean hasMentor() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'mentor' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.kafka.avro.Mentor.Builder getMentorBuilder() {
      if (mentorBuilder == null) {
        if (hasMentor()) {
          setMentorBuilder(com.kafka.avro.Mentor.newBuilder(mentor));
        } else {
          setMentorBuilder(com.kafka.avro.Mentor.newBuilder());
        }
      }
      return mentorBuilder;
    }

    /**
     * Sets the Builder instance for the 'mentor' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.kafka.avro.AssignmentNotification.Builder setMentorBuilder(com.kafka.avro.Mentor.Builder value) {
      clearMentor();
      mentorBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'mentor' field has an active Builder instance
     * @return True if the 'mentor' field has an active Builder instance
     */
    public boolean hasMentorBuilder() {
      return mentorBuilder != null;
    }

    /**
      * Clears the value of the 'mentor' field.
      * @return This builder.
      */
    public com.kafka.avro.AssignmentNotification.Builder clearMentor() {
      mentor = null;
      mentorBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'students' field.
      * @return The value.
      */
    public java.util.List<com.kafka.avro.Student> getStudents() {
      return students;
    }


    /**
      * Sets the value of the 'students' field.
      * @param value The value of 'students'.
      * @return This builder.
      */
    public com.kafka.avro.AssignmentNotification.Builder setStudents(java.util.List<com.kafka.avro.Student> value) {
      validate(fields()[1], value);
      this.students = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'students' field has been set.
      * @return True if the 'students' field has been set, false otherwise.
      */
    public boolean hasStudents() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'students' field.
      * @return This builder.
      */
    public com.kafka.avro.AssignmentNotification.Builder clearStudents() {
      students = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AssignmentNotification build() {
      try {
        AssignmentNotification record = new AssignmentNotification();
        if (mentorBuilder != null) {
          try {
            record.mentor = this.mentorBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("mentor"));
            throw e;
          }
        } else {
          record.mentor = fieldSetFlags()[0] ? this.mentor : (com.kafka.avro.Mentor) defaultValue(fields()[0]);
        }
        record.students = fieldSetFlags()[1] ? this.students : (java.util.List<com.kafka.avro.Student>) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AssignmentNotification>
    WRITER$ = (org.apache.avro.io.DatumWriter<AssignmentNotification>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AssignmentNotification>
    READER$ = (org.apache.avro.io.DatumReader<AssignmentNotification>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    this.mentor.customEncode(out);

    long size0 = this.students.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (com.kafka.avro.Student e0: this.students) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (this.mentor == null) {
        this.mentor = new com.kafka.avro.Mentor();
      }
      this.mentor.customDecode(in);

      long size0 = in.readArrayStart();
      java.util.List<com.kafka.avro.Student> a0 = this.students;
      if (a0 == null) {
        a0 = new SpecificData.Array<com.kafka.avro.Student>((int)size0, SCHEMA$.getField("students").schema());
        this.students = a0;
      } else a0.clear();
      SpecificData.Array<com.kafka.avro.Student> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.kafka.avro.Student>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          com.kafka.avro.Student e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new com.kafka.avro.Student();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (this.mentor == null) {
            this.mentor = new com.kafka.avro.Mentor();
          }
          this.mentor.customDecode(in);
          break;

        case 1:
          long size0 = in.readArrayStart();
          java.util.List<com.kafka.avro.Student> a0 = this.students;
          if (a0 == null) {
            a0 = new SpecificData.Array<com.kafka.avro.Student>((int)size0, SCHEMA$.getField("students").schema());
            this.students = a0;
          } else a0.clear();
          SpecificData.Array<com.kafka.avro.Student> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.kafka.avro.Student>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              com.kafka.avro.Student e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new com.kafka.avro.Student();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










