/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.kafka.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Student extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2982060204375742485L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Student\",\"namespace\":\"com.kafka.avro\",\"fields\":[{\"name\":\"studentName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"studentEmail\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Student> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Student> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Student> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Student> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Student> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Student to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Student from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Student instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Student fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String studentName;
  private java.lang.String studentEmail;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Student() {}

  /**
   * All-args constructor.
   * @param studentName The new value for studentName
   * @param studentEmail The new value for studentEmail
   */
  public Student(java.lang.String studentName, java.lang.String studentEmail) {
    this.studentName = studentName;
    this.studentEmail = studentEmail;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return studentName;
    case 1: return studentEmail;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: studentName = value$ != null ? value$.toString() : null; break;
    case 1: studentEmail = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'studentName' field.
   * @return The value of the 'studentName' field.
   */
  public java.lang.String getStudentName() {
    return studentName;
  }


  /**
   * Sets the value of the 'studentName' field.
   * @param value the value to set.
   */
  public void setStudentName(java.lang.String value) {
    this.studentName = value;
  }

  /**
   * Gets the value of the 'studentEmail' field.
   * @return The value of the 'studentEmail' field.
   */
  public java.lang.String getStudentEmail() {
    return studentEmail;
  }


  /**
   * Sets the value of the 'studentEmail' field.
   * @param value the value to set.
   */
  public void setStudentEmail(java.lang.String value) {
    this.studentEmail = value;
  }

  /**
   * Creates a new Student RecordBuilder.
   * @return A new Student RecordBuilder
   */
  public static com.kafka.avro.Student.Builder newBuilder() {
    return new com.kafka.avro.Student.Builder();
  }

  /**
   * Creates a new Student RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Student RecordBuilder
   */
  public static com.kafka.avro.Student.Builder newBuilder(com.kafka.avro.Student.Builder other) {
    if (other == null) {
      return new com.kafka.avro.Student.Builder();
    } else {
      return new com.kafka.avro.Student.Builder(other);
    }
  }

  /**
   * Creates a new Student RecordBuilder by copying an existing Student instance.
   * @param other The existing instance to copy.
   * @return A new Student RecordBuilder
   */
  public static com.kafka.avro.Student.Builder newBuilder(com.kafka.avro.Student other) {
    if (other == null) {
      return new com.kafka.avro.Student.Builder();
    } else {
      return new com.kafka.avro.Student.Builder(other);
    }
  }

  /**
   * RecordBuilder for Student instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Student>
    implements org.apache.avro.data.RecordBuilder<Student> {

    private java.lang.String studentName;
    private java.lang.String studentEmail;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.kafka.avro.Student.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.studentName)) {
        this.studentName = data().deepCopy(fields()[0].schema(), other.studentName);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.studentEmail)) {
        this.studentEmail = data().deepCopy(fields()[1].schema(), other.studentEmail);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing Student instance
     * @param other The existing instance to copy.
     */
    private Builder(com.kafka.avro.Student other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.studentName)) {
        this.studentName = data().deepCopy(fields()[0].schema(), other.studentName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.studentEmail)) {
        this.studentEmail = data().deepCopy(fields()[1].schema(), other.studentEmail);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'studentName' field.
      * @return The value.
      */
    public java.lang.String getStudentName() {
      return studentName;
    }


    /**
      * Sets the value of the 'studentName' field.
      * @param value The value of 'studentName'.
      * @return This builder.
      */
    public com.kafka.avro.Student.Builder setStudentName(java.lang.String value) {
      validate(fields()[0], value);
      this.studentName = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'studentName' field has been set.
      * @return True if the 'studentName' field has been set, false otherwise.
      */
    public boolean hasStudentName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'studentName' field.
      * @return This builder.
      */
    public com.kafka.avro.Student.Builder clearStudentName() {
      studentName = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'studentEmail' field.
      * @return The value.
      */
    public java.lang.String getStudentEmail() {
      return studentEmail;
    }


    /**
      * Sets the value of the 'studentEmail' field.
      * @param value The value of 'studentEmail'.
      * @return This builder.
      */
    public com.kafka.avro.Student.Builder setStudentEmail(java.lang.String value) {
      validate(fields()[1], value);
      this.studentEmail = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'studentEmail' field has been set.
      * @return True if the 'studentEmail' field has been set, false otherwise.
      */
    public boolean hasStudentEmail() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'studentEmail' field.
      * @return This builder.
      */
    public com.kafka.avro.Student.Builder clearStudentEmail() {
      studentEmail = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Student build() {
      try {
        Student record = new Student();
        record.studentName = fieldSetFlags()[0] ? this.studentName : (java.lang.String) defaultValue(fields()[0]);
        record.studentEmail = fieldSetFlags()[1] ? this.studentEmail : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Student>
    WRITER$ = (org.apache.avro.io.DatumWriter<Student>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Student>
    READER$ = (org.apache.avro.io.DatumReader<Student>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.studentName);

    out.writeString(this.studentEmail);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.studentName = in.readString();

      this.studentEmail = in.readString();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.studentName = in.readString();
          break;

        case 1:
          this.studentEmail = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










